### ISSUE TITLE
New Feature: create-mobi

### ISSUE THREAD

**Issue by sasagr** [leoncvlt/blinkist-scraper#25]
add the possibility to create-mobi file

I see that ebooklib does not supper mobi but I found this
https://github.com/jachinlin/kindle_maker

if interested it could be added to generate also mobi files

**Comment by leoncvlt** [comment]
Feels like a bit of a redundant feature, since .mobi is mainly a kindle-specific format, and kindles support .epub files out of the box anyway. Plus it would introduce a few closed-source dependencies like Amazon's KindleGen tool which is required by that library linked above. Any particular advantages to having this? 🤔

**Comment by sasagr** [comment]
AFAIK kindle does not support ePub format, you need to convert it to mobi

**Comment by leoncvlt** [comment]
Ah you're right, fair enough - I just took conversion for granted as I use [Calibre](https://calibre-ebook.com/) to manage all of my ebooks and it handles it effortlessly

**Comment by Arminius4** [comment]
[Mobi is an old format ](https://en.wikipedia.org/wiki/Comparison_of_e-book_formats)with some restrictions based on the Open eBook standard which has been superseded by ePub. [Apparently, the new Kindles do not only support but even recommend to use ePub instead of mobi](https://kdp.amazon.com/en_US/help/topic/G200634390).
I also use Calibre for my eBook collection and can recommend it for conversions between different formats and management of different devices.
