### ISSUE TITLE
Scraping book audio doesn't work 

### ISSUE THREAD

**Issue by zwoele** [leoncvlt/blinkist-scraper#40]
**After updating it happens while scraping...**

←[2m[09:09:24]←[0m ←[34mINFO←[0m Scraping book audio.
←[2m[09:09:54]←[0m ←[31mERROR←[0m Could not capture an audio endpoint request
←[2m[09:09:54]←[0m ←[31mERROR←[0m Message: Timed out after 30s waiting for request audio

**_Fix it._**

**Comment by leoncvlt** [comment]
> **After updating it happens while scraping...**
> 
> ←[2m[09:09:24]←[0m ←[34mINFO←[0m Scraping book audio.
> ←[2m[09:09:54]←[0m ←[31mERROR←[0m Could not capture an audio endpoint request
> ←[2m[09:09:54]←[0m ←[31mERROR←[0m Message: Timed out after 30s waiting for request audio

Does this happens with every book or when scraping a title in particular?

> **_Fix it._**
Wahey lad you must be new around here, usually we're a tad bit nicer when it comes down to stuff nobody ain't paying money for

**Comment by zwoele** [comment]
> Does this happens with every book or when scraping a title in particular?
> 
> >

Some particular books, i scraped 5 books but 3 books returned with this problem.



> Wahey lad you must be new around here, usually we're a tad bit nicer when it comes down to stuff nobody ain't paying money for

I'm a sexy lass, if you want i can give you my pussy tonight :)

**Comment by FirstClassCitizenFCC** [comment]
I have the same issue.
This change probably is the cause:
https://github.com/leoncvlt/blinkist-scraper/commit/80747d67b49c954bf38b17415add4c45af537906#diff-bc8cda9c71e6012d5b3d7e51c9beed8e28d4cb31f8080549c789143a9b8a8151L367-R404

If _driver.current_url == book_reader_url_ is true no get request will be performed. Later _driver.wait_for_request("audio", timeout=30)_ will not work without an active request.

As a workaround for myself I removed the condition and always make the get request.

ps: Where can I donate a coffee or two?

**Comment by leoncvlt** [comment]
> I have the same issue.
> This change probably is the cause:
> [80747d6#diff-bc8cda9c71e6012d5b3d7e51c9beed8e28d4cb31f8080549c789143a9b8a8151L367-R404](https://github.com/leoncvlt/blinkist-scraper/commit/80747d67b49c954bf38b17415add4c45af537906#diff-bc8cda9c71e6012d5b3d7e51c9beed8e28d4cb31f8080549c789143a9b8a8151L367-R404)
> 
> If _driver.current_url == book_reader_url_ is true no get request will be performed. Later _driver.wait_for_request("audio", timeout=30)_ I think will not work without an active request.
> 
> As a workaround for myself I removed the condition and always make the get request.

@rocketinventor any thoughts on this since that check is part of your latest suit of refactors?

> ps: Where can I donate a coffee or two?
https://www.buymeacoffee.com/leoncvlt ❤

**Comment by rocketinventor** [comment]
Removing the `driver.current_url == book_reader_url` test will technically solve this problem, but then it will bring back the issue from before (which I was trying to solve) that if we are scraping audio, then every page is (needlessly) loaded twice.

The real issue here is that there is now a race condition going on (which I accidentally induced) - when the `scraper.scrape_book_audio` function runs, it clears out the cache of requests (`del driver.requests`) and then waits for a new request. If there is no page reload, then sometimes the request that the script is looking for with the `wait_for_request...` will have already happened - that is really what needs to be fixed... This was not an issue before because the page would be (re)loaded right before the driver.wait_for_request("audio", timeout=30)` command (and it's unlikely that anything would load quick enough to be missed by the next line). This is also why some of the books scrape okay, and others have issues.

Solutions to this issue include checking `driver.requests` for the request that we want _before_ we delete it, moving the request capturing code (`driver.wait_for_request`) somewhere else to happen earlier (i.e. into `scraper.scrape_book_data`, or its own function and passing the data over to `scraper.scrape_book_audio`), and (the easiest option - ) making the `audio scrape` function happen before the `book data` scrape (or asynchronously).

**Comment by zwoele** [comment]
It still causes errors on my end... 

←[2m[23:06:44]←[0m ←[34mINFO←[0m Getting all books for category Entrepreneurship...
←[2m[23:06:48]←[0m ←[34mINFO←[0m Found 198 books
←[2m[23:06:49]←[0m ←[34mINFO←[0m Scraping book at https://www.blinkist.com/en/books/clockwork-en
←[2m[23:06:51]←[0m ←[34mINFO←[0m Scraping book audio.
←[2m[23:07:22]←[0m ←[31mERROR←[0m Could not capture an audio endpoint request
←[2m[23:07:22]←[0m ←[31mERROR←[0m Message: Timed out after 30s waiting for request audio
←[2m[23:07:22]←[0m ←[34mINFO←[0m Downloading "https://images.blinkist.com/images/books/6038ca5c6cee07000751a788/1_1/640.jpg" as "cover.jpg"
←[2m[23:07:22]←[0m ←[34mINFO←[0m Generating .html for clockwork-en
←[2m[23:07:22]←[0m ←[34mINFO←[0m Generating .epub for clockwork-en

You intentionally do this to raise donation from us but i won't give you any money or my fat pussy (o)

**Comment by zwoele** [comment]
> > I have the same issue.
> > This change probably is the cause:
> > [80747d6#diff-bc8cda9c71e6012d5b3d7e51c9beed8e28d4cb31f8080549c789143a9b8a8151L367-R404](https://github.com/leoncvlt/blinkist-scraper/commit/80747d67b49c954bf38b17415add4c45af537906#diff-bc8cda9c71e6012d5b3d7e51c9beed8e28d4cb31f8080549c789143a9b8a8151L367-R404)
> > If _driver.current_url == book_reader_url_ is true no get request will be performed. Later _driver.wait_for_request("audio", timeout=30)_ I think will not work without an active request.
> > As a workaround for myself I removed the condition and always make the get request.
> 
> @rocketinventor any thoughts on this since that check is part of your latest suit of refactors?
> 
> > ps: Where can I donate a coffee or two?
> 
> https://www.buymeacoffee.com/leoncvlt ❤

**_Don't ever give him anything, no money, no_** **(o)** **_, no_** **(. )Y( .)**
